volumes:
  n8n_database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stacheldrath/Desktop/0xDEADBEEF/n8n/database

networks:
  n8n-net:

services:
  n8n_database:
    image: postgres:16
    container_name: n8n_database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=stacheldrath
      - POSTGRES_PASSWORD=stacheldrath
      - POSTGRES_DB=n8n_db
      - POSTGRES_NON_ROOT_USER=stacheldrath_non_root
      - POSTGRES_NON_ROOT_PASSWORD=stacheldrath_non_root
    volumes:
      - n8n_database:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -D ${POSTGREST_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      n8n-net:

  n8n_vectordb:
    build: vectordb
    container_name: n8n_vectordb
    restart: unless-stopped
    environment:
      - POSTGRES_USER=stacheldrath
      - POSTGRES_PASSWORD=stacheldrath
      - POSTGRES_DB=n8n_vectordb
      - POSTGRES_NON_ROOT_USER=stacheldrath_non_root
      - POSTGRES_NON_ROOT_PASSWORD=stacheldrath_non_root
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -D ${POSTGREST_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      n8n-net:

  n8n_app:
    image: docker.n8n.io/n8nio/n8n:2.3.0
    container_name: n8n_app
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_database
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_USER=stacheldrath
      - DB_POSTGRESDB_PASSWORD=stacheldrath
      - N8N_EDITOR_BASE_URL=http://n8n.hackwerk.abc
      - N8N_WEBHOOK_URL=http://n8n.hackwerk.abc
      - N8N_RUNNERS_ENABLED=true
      - N8N_RUNNERS_MODE=external
      - N8N_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - N8N_RUNNERS_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjdkOTZmMC00YjRlLTRjMjUtYjkyZC0yZWFlOGQ1OGQzYzQiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzY1OTc0NTE4fQ.3isc6n-G5E2e_OXSvED0B0sBTuYRtDZEwa1XpzAfu-4
      - N8N_NATIVE_PYTHON_RUNNER=true
      - N8N_PYTHON_MODULE_ALLOW_LIST=random
      - EXPRESS_TRUST_PROXY=true
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - WEBHOOK_URL=http://n8n.hackwerk.abc
      - TZ=Europe/Amsterdam
    links:
      - n8n_database
    volumes:
      - n8n_database:/home/node/.n8n
      - evidence:/home/node/.n8n-files/documents
    networks:
      - stacheldrath-net
      - n8n-net
    depends_on:
      n8n_database:
        condition: service_healthy

  n8n_runners:
    build: ./n8n-runners
    container_name: n8n_runners
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n_app:5679
      - N8N_RUNNERS_AUTH_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ZjdkOTZmMC00YjRlLTRjMjUtYjkyZC0yZWFlOGQ1OGQzYzQiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzY1OTc0NTE4fQ.3isc6n-G5E2e_OXSvED0B0sBTuYRtDZEwa1XpzAfu-4
      - N8N_RUNNERS_STDLIB_ALLOW=*
    depends_on:
      - n8n_app
    networks:
      - n8n-net

