volumes:
  kali_root:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stacheldrath/Desktop/0xDEADBEEF/kali

networks:
  kali-net:

services:
  kali_code:
    build: ./kali_code
    container_name: kali_code
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - kali_root:/root
      - evidence:/root/Documents
    networks:
      - kali-net

  kali_mcp:
    build: ./kali_mcp
    container_name: kali_mcp
    restart: unless-stopped
    depends_on:
      - kali_code
    networks:
      - stacheldrath-net
      - kali-net
