include:
  - services/nextcloud/docker-compose.yml
  - services/n8n/docker-compose.yml
  - services/torxng/docker-compose.yml
#  - services/osm/docker-compose.yml

volumes:
  evidence:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/stacheldrath/Desktop/0xDEADBEEF/evidence

networks:
  stacheldrath-net:

services:
  stacheldrath_proxy:
    image: nginx:latest
    container_name: stacheldrath_proxy
    depends_on:
      - nextcloud_app
      - n8n_app
